name: swell-foop
adopt-info: swell-foop
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

slots:
  # for GtkApplication registration
  swell-foop:
    interface: dbus
    bus: session
    name: org.gnome.SwellFoop

apps:
  swell-foop:
    command: usr/bin/swell-foop
    extensions: [gnome]
    plugs:
      - opengl
    desktop: usr/share/applications/org.gnome.SwellFoop.desktop
    common-id: org.gnome.SwellFoop.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      DISABLE_WAYLAND: 'true'

parts:
  swell-foop:
    source: https://gitlab.gnome.org/GNOME/swell-foop.git
    source-type: git
    source-tag: '41.1'
    source-depth: 1
    plugin: meson
    meson-parameters: [--prefix=/snap/swell-foop/current/usr]
    parse-info: [usr/share/metainfo/org.gnome.SwellFoop.appdata.xml]
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
    override-build: |
      sed -i.bak -e 's|Icon=org.gnome.SwellFoop$|Icon=${SNAP}/meta/gui/org.gnome.SwellFoop.png|g' $CRAFT_PART_SRC/data/org.gnome.SwellFoop.desktop.in
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/512x512/apps/org.gnome.SwellFoop.png $CRAFT_PART_INSTALL/meta/gui/
      cp ../install/snap/swell-foop/current/usr/share/applications/org.gnome.SwellFoop.desktop $CRAFT_PART_INSTALL/meta/gui/
    organize:
      snap/swell-foop/current/usr: usr
